apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: inceptionv3
  name: $(svcName)
  namespace: kubeflow
spec:
  template:
    metadata:
      labels:
        app: inceptionv3
        version: v1
    spec:
      containers:
      - args:
        - --port=9000
        - --rest_api_port=8500
        - --model_name=inceptionv3
        - --model_base_path=$(modelBasePath)
        - --tensorflow_intra_op_parallelism=$(TENSORFLOW_INTRA_OP_PARALLELISM)
        - --tensorflow_inter_op_parallelism=$(TENSORFLOW_INTER_OP_PARALLELISM)
        - --monitoring_config_file=/var/config/monitoring_config.txt
        command:
        - /usr/bin/tensorflow_model_server
        env:
        - name: modelBasePath
          value: $(modelBasePath)
        - name: OMP_NUM_THREADS
          value: $(OMP_NUM_THREADS)
        image: docker.io/karthikvadla/kfserving:intel-mkl-1.13.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 9000
        name: inceptionv3
        ports:
        - containerPort: 9000
        - containerPort: 8500
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/config/
          name: config-volume
      volumes:
      - configMap:
          name: inceptionv3-deploy-config
        name: config-volume
