apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- inceptionv3-deploy-config.yaml
- service.yaml

namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.name
  name: svcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inceptionv3-map-serving
- fieldref:
    fieldPath: data.modelBasePath
  name: modelBasePath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inceptionv3-map-serving
- fieldref:
    fieldPath: data.OMP_NUM_THREADS
  name: OMP_NUM_THREADS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inceptionv3-map-serving
- fieldref:
    fieldPath: data.TENSORFLOW_INTER_OP_PARALLELISM
  name: TENSORFLOW_INTER_OP_PARALLELISM
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inceptionv3-map-serving
- fieldref:
    fieldPath: data.TENSORFLOW_INTRA_OP_PARALLELISM
  name: TENSORFLOW_INTRA_OP_PARALLELISM
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inceptionv3-map-serving
